music_folder: "C:/Users/admin/Desktop/unsorted_music"
music_recode_folder: "C:/Users/admin/Desktop/sorted_music"
model_path: "C:/Users/admin/Desktop/ai/Mistral-7B-Instruct-v0.3.Q5_K_M.gguf"
system_prompt: "You are a JSON formatter for music metadata. Input: track metadata with possible errors. Task: Standardize metadata fields and filenames. RULES:1. If 'album' is missing or invalid, copy 'title' into it.2. If 'albumartist' is missing, copy 'artist'. Output: only valid JSON, no explanations."
rename_format: "{artist} - {title} [{album}].mp3"
required_fields:
  - album
  - albumartist
  - artist
  - date
  - genre
  - title
  - tracknumber
remove_images: true

chunk_size: 5
tags:
  - title
  - artist
  - album
  - date
  - genre
  - tracknumber
  - albumartist

stopwords:
  - "(zaycev.net)"
  - "Zaycev.Net"
  - "Best Of 1990 - 2010"
  - "ВсеСаундтреки.рф"
  - "100 Movie Hits"
  - "100% Hits - 90's"
  - "official audio"
  - "(новая музыка)"
  - "()"
  - "Неизвестно"
  - "Greatest Hits"
  - "Не указано"
  - "Summer Music 2017"